/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum_in {
	struct {
		u_int data_len;
		int *data_val;
	} data;
};
typedef struct sum_in sum_in;

struct sum_out {
	int res1;
};
typedef struct sum_out sum_out;

#define SUM_PROG 0x31230000
#define SUM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMPROC 1
extern  sum_out * sumproc_1(sum_in *, CLIENT *);
extern  sum_out * sumproc_1_svc(sum_in *, struct svc_req *);
extern int sum_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMPROC 1
extern  sum_out * sumproc_1();
extern  sum_out * sumproc_1_svc();
extern int sum_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum_in (XDR *, sum_in*);
extern  bool_t xdr_sum_out (XDR *, sum_out*);

#else /* K&R C */
extern bool_t xdr_sum_in ();
extern bool_t xdr_sum_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
