/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sum.h"

bool_t
xdr_sum_in (XDR *xdrs, sum_in *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sum_out (XDR *xdrs, sum_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res1))
		 return FALSE;
	return TRUE;
}
