/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct readargs {
	int fhandle;
	char *filename;
	int offset;
	int count;
};
typedef struct readargs readargs;

struct readres {
	int status;
	char *data;
};
typedef struct readres readres;

struct writeargs {
	int fhandle;
	char *filename;
	int offset;
	int count;
	char *data;
};
typedef struct writeargs writeargs;

struct writeres {
	int status;
};
typedef struct writeres writeres;

struct filelist {
	char *data;
	char *delim;
};
typedef struct filelist filelist;

#define NFS_PROG 0x31230000
#define NFS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define NFS_LS 1
extern  filelist * nfs_ls_1(void *, CLIENT *);
extern  filelist * nfs_ls_1_svc(void *, struct svc_req *);
#define NFS_READ 2
extern  readres * nfs_read_1(readargs *, CLIENT *);
extern  readres * nfs_read_1_svc(readargs *, struct svc_req *);
#define NFS_WRITE 3
extern  writeres * nfs_write_1(writeargs *, CLIENT *);
extern  writeres * nfs_write_1_svc(writeargs *, struct svc_req *);
extern int nfs_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define NFS_LS 1
extern  filelist * nfs_ls_1();
extern  filelist * nfs_ls_1_svc();
#define NFS_READ 2
extern  readres * nfs_read_1();
extern  readres * nfs_read_1_svc();
#define NFS_WRITE 3
extern  writeres * nfs_write_1();
extern  writeres * nfs_write_1_svc();
extern int nfs_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_readargs (XDR *, readargs*);
extern  bool_t xdr_readres (XDR *, readres*);
extern  bool_t xdr_writeargs (XDR *, writeargs*);
extern  bool_t xdr_writeres (XDR *, writeres*);
extern  bool_t xdr_filelist (XDR *, filelist*);

#else /* K&R C */
extern bool_t xdr_readargs ();
extern bool_t xdr_readres ();
extern bool_t xdr_writeargs ();
extern bool_t xdr_writeres ();
extern bool_t xdr_filelist ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
